app/urls.py
from django.contrib import admin
from django.urls import path
from main import views
from django.contrib.auth import views as auth_views


app_name = "main"


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.submit_form, name="main"),
    path("login/", views.login_view, name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="main"), name="logout"),
    path("faq/", views.faq, name="faq"),
    path("my_forms/", views.my_forms, name="my_forms"),
    path("forms_list", views.forms_list, name="forms_list"),
    path(
        "forms_list/<int:form_id>/", views.form_detail_assign, name="form_detail_assign"
    ),
    path("faq/", views.faq, name="faq"),
    path(
        "my_forms/<int:form_id>/",
        views.employee_form_detail,
        name="employee_form_detail",
    ),
]

main/models.py
from django.db import models

# Create your models here.


class Employee(models.Model):
    employee_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=64)
    name = models.CharField(max_length=64)
    surname = models.CharField(max_length=64)
    email = models.CharField(max_length=64)

    class Meta:
        db_table = "employee"
        permissions = [
            ("can_assign_form", "Can assign forms to employees"),
        ]

    def __str__(self):
        return f"{self.name} {self.surname}"


class Form(models.Model):
    CATEGORY_CHOICES = [
        ("Проблемы с интернетом", "Проблемы с интернетом"),
        (
            "Проблемы с периферийным оборудованием",
            "Проблемы с периферийным оборудованием",
        ),
        ("Проблемы с электронной почтой", "Проблемы с электронной почтой"),
        ("Другие проблемы", "Другие проблемы"),
    ]
    STATUS_CHOICES = [
        ("обрабатывается", "обрабатывается"),
        ("не назначен", "не назначен"),
        ("завершен", "завершен"),
    ]

    form_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=64)
    phone = models.CharField(max_length=64)
    category = models.CharField(
        max_length=64, choices=CATEGORY_CHOICES, null=True, blank=True
    )
    comment = models.CharField(max_length=200)
    submitted_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="не назначен"
    )

    class Meta:
        db_table = "form"

    def __str__(self):
        return f"{self.name} ({self.email})"


class FormAssignment(models.Model):
    STATUS_CHOICES = [
        ("не назначен", "не назначен"),
        ("обрабатывается", "обрабатывается"),
        ("завершен", "завершен"),
    ]

    assignment_id = models.AutoField(primary_key=True)
    form = models.ForeignKey(Form, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    assigned_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="не назначен"
    )
    finished_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "form_assignment"
        unique_together = ("form", "employee")

    def __str__(self):
        return f"Assignment #{self.assignment_id} - Form {self.form_id} to Employee {self.employee_id}"

templates/base.html
{% load static %} {% load group_tags %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %}Служба технической поддержки{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Alegreya:ital,wght@0,400..900;1,400..900&family=Gentium+Plus:ital,wght@0,400;0,700;1,400;1,700&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="page-wrapper">
      <header class="site-header">
        <div class="container header-inner">
          <h1 class="site-title">
            <a href="http://tech-podderjka64583-site.home.onhh.ru/">Служба технической поддержки</a>
          </h1>
          <nav class="site-nav">
            {% if user.is_authenticated %}
            <div class="nav-left">
              <a href="http://tech-podderjka64583-site.home.onhh.ru/"> Главная страница <a>
              <a href="{% url 'main' %}">Оставить заявку</a>
              {% if user|has_group:"admin" %}
              <a href="{% url 'forms_list' %}">Список заявок</a>
              {% elif user|has_group:"employee" %}
              <a href="{% url 'my_forms' %}">Мои заявки</a>
              {% endif %}
              <a href="{% url 'faq' %}">FAQ</a>
            </div>
            <div class="nav-right">
              <span class="username">{{ user.username }}</span>
              <form
                method="post"
                action="{% url 'logout' %}"
                style="display: inline"
              >
                {% csrf_token %}
                <button type="submit" class="logout-button">Выйти</button>
              </form>
            </div>
            {% else %}
            <div class="nav-unauthenticated">
              <a href="http://tech-podderjka64583-site.home.onhh.ru/"> Главная страница <a>
              <a href="{% url 'main' %}">Оставить заявку</a>
              <a href="{% url 'faq' %}">FAQ</a>
              <a href="{% url 'login' %}">Войти</a>
            </div>
            {% endif %}
          </nav>
        </div>
      </header>

      <hr class="header-separator" />

      <main class="content-wrapper">
        <div class="container content">{% block content %} {% endblock %}</div>
      </main>

      <footer class="site-footer">
        <div class="container">
          <p>Copyright © 2025 Служба технической поддержки</p>
        </div>
      </footer>
    </div>
  </body>
</html>

templates/employee_form_detail.html
{% extends "base.html" %} {% load static %} {% block title %}Детали
заявки{%endblock%} {%block content%}

<div class="form-detail-content">
  <h2>Заявка #{{ form.form_id }}</h2>

  <ul>
    <li><strong>Имя:</strong> {{ form.name }}</li>
    <li><strong>Email:</strong> {{ form.email }}</li>
    <li><strong>Телефон:</strong> {{ form.phone }}</li>
    <li><strong>Категория:</strong> {{ form.category }}</li>
    <li><strong>Комментарий пользователя:</strong> {{ form.comment }}</li>
    <li>
      <strong>Дата подачи:</strong> {{ form.submitted_at|date:"d.m.Y H:i" }}
    </li>
    <li><strong>Статус:</strong> {{ form.status }}</li>
  </ul>

  <h3>Статус назначения</h3>
  <ul>
    <li><strong>Статус:</strong> {{ assignment.status }}</li>
    <li>
      <strong>Дата назначения:</strong>
      {{assignment.assigned_at | date:"d.m.Y H:i"}}
    </li>
    <li>
      <strong>Дата завершения:</strong>
      {%if assignment.finished_at%} {{assignment.finished_at|date:"d.m.YH:i"}}
      {%else%}—{% endif %}
    </li>
  </ul>

  {% if assignment.status != "завершен" %}
  <form method="post" style="margin-top: 20px">
    {% csrf_token %}
    <button type="submit" class="btn btn-success">
      Завершить работу над заявкой
    </button>
  </form>
  {% else %}
  <p>Заявка уже завершена.</p>
  {% endif %}

  <a href="{% url 'my_forms' %}">← Назад к моим заявкам</a>
</div>
{% endblock %}

templates/faq.html
{% extends "base.html" %} {% load static %} {% block title %}FAQ{% endblock %}
{% block content %}
<h2>Часто задаваемые вопросы (FAQ)</h2>
<div class="faq-container">
  <ol>
    <li>
      <strong>Как создать заявку на техническую поддержку?</strong><br />
      Перейдите в раздел «Оставить заявку», опишите суть вашей проблемы и
      нажмите «Отправить». Ваша заявка будет автоматически зарегистрирована в
      системе.
    </li>
    <li>
      <strong>Сколько времени обрабатывается заявка?</strong><br />
      Среднее время ожидания ответа зависит от сложности вопроса, но как
      правило, первые отклики приходят в течение 1 рабочего дня.
    </li>
    <li>
      <strong>Кто может воспользоваться системой технической поддержки?</strong
      ><br />
      Сервис доступен для всех студентов и сотрудников Московского университета
      имени С.Ю. Витте.
    </li>
    <li>
      <strong
        >Нужно ли создавать новую заявку, если проблема повторяется?</strong
      ><br />
      Да, для каждого нового случая нужно оформлять отдельную заявку, чтобы
      специалисты могли корректно отследить и решить вопрос.
    </li>
    <li>
      <strong>Как узнать, что моя заявка решена?</strong><br />
      После обработки вашей заявки вы получите уведомление по электронной почте.
    </li>
    <li>
      <strong>Что делать, если заявка долго не обрабатывается?</strong><br />
      Если заявка не получает ответа более 3 рабочих дней, вы можете написать
      комментарий к заявке для уточнения или создать новое обращение с пометкой
      «Срочно».
    </li>
    <li>
      <strong>Кто рассматривает заявки?</strong><br />
      Заявки рассматривают сотрудники Департамента электронного обучения и
      сопровождения Московского университета имени С.Ю. Витте.
    </li>
    <li>
      <strong>Можно ли удалить отправленную заявку?</strong><br />
      Удалить заявку самостоятельно нельзя, но вы можете оставить комментарий с
      пометкой «Актуальность утрачена», и она будет закрыта модератором.
    </li>
    <li>
      <strong>Что делать, если сайт технической поддержки недоступен?</strong
      ><br />
      В случае сбоя сервиса, вы можете обратиться по телефону или написать на
      официальный электронный адрес департамента.
    </li>
    <li>
      <strong
        >Можно ли обращаться в службу поддержки по вопросам, не связанным с
        обучением?</strong
      ><br />
      Сервис предназначен только для поддержки по вопросам, связанным с
      использованием образовательной инфраструктуры и ИТ-сервисов университета.
    </li>
    <li>
      <strong>Как понять, что моя заявка была принята в работу?</strong><br />
      После отправки заявки вы получите уведомление на электронную почту.
    </li>
  </ol>
</div>
{% endblock %}

templates/form_detail_assign.html
{% extends "base.html" %}
{%load static%}
{% block title %}Назначение заявки{% endblock %}

{% block content %}

<div class="form-detail-content">
    <h2>Заявка #{{ form.form_id }}</h2>
    <ul>
    <li><strong>Имя:</strong> {{ form.name }}</li>
    <li><strong>Email:</strong> {{ form.email }}</li>
    <li><strong>Телефон:</strong> {{ form.phone }}</li>
    <li><strong>Категория:</strong> {{ form.category }}</li>
    <li><strong>Комментарий пользователя:</strong> {{ form.comment }}</li>
    <li><strong>Дата подачи:</strong> {{ form.submitted_at|date:"d.m.Y H:i" }}</li>
    <li><strong>Статус:</strong> {{ form.status }}</li>
    </ul>

    <h3>Назначения</h3>
    {% if assignments %}
    <table>
    <thead>
        <tr>
        <th>Сотрудник</th>
        <th>Статус</th>
        <th>Дата назначения</th>
        <th>Дата завершения</th>
        </tr>
    </thead>
    <tbody>
        {% for a in assignments %}
        <tr>
        <td>{{ a.employee }}</td>
        <td>{{ a.status }}</td>
        <td>{{ a.assigned_at|date:"d.m.Y H:i" }}</td>
        <td>{% if a.finished_at %}{{ a.finished_at|date:"d.m.Y H:i" }}{% else %}—{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    {% else %}
    <p>Назначений ещё нет.</p>
    {% endif %}

    <h3>Назначить сотрудника</h3>
    <form method="post">
    {% csrf_token %}
    <label for="employee">Выберите сотрудника:</label>
    <select name="employee" id="employee" required>
        <option value="">-- Выберите сотрудника --</option>
        {% for emp in employees %}
        <option value="{{ emp.pk }}">{{ emp }}</option>
        {% endfor %}
    </select>
    <button type="submit">Назначить</button>
    </form>

    <a href="{% url 'forms_list' %}">← Назад к списку заявок</a>

    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock %}

templates/forms_list.html
{% extends "base.html" %} {% load static %} {% block title %} Список заявок
{%endblock%} {% block content %}
<h2>Список заявок</h2>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Категория</th>
      <th>Комментарий</th>
      <th>Дата подачи</th>
      <th>Дата назначения</th>
      <th>Статус</th>
      <th>Дата завершения</th>
      <th>Назначенный сотрудник</th>
      <th>Действия</th>
    </tr>
  </thead>
  <tbody>
    {% for form in forms %}
    <tr>
      <td>{{ form.form_id }}</td>
      <td>{{ form.category }}</td>
      <td>{{ form.comment }}</td>
      <td>{{ form.submitted_at|date:"d.m.Y H:i" }}</td>
      <td>{{ form.latest_assignment_assigned_at|date:"d.m.Y H:i" }}</td>

      <td>
        <span
          class="status-box {% if form.latest_assignment_status %} {% if form.latest_assignment_status == 'обрабатывается' %}yellow {% elif form.latest_assignment_status == 'не назначен' %}red {% elif form.latest_assignment_status == 'завершен' %}green {% endif %} {% else %} {% if form.status == 'обрабатывается' %}yellow {% elif form.status == 'не назначен' %}red {% elif form.status == 'завершен' %}green {% endif %} {% endif %}"
        >
          {{ form.latest_assignment_status|default:form.status }}
        </span>
      </td>
      <td>
        {{ form.latest_assignment_finished_at|date:"d.m.Y H:i"|default:"—" }}
      </td>
      <td>
        {% if form.assigned_employee_name and form.assigned_employee_surname %}
        {{ form.assigned_employee_name }} {{ form.assigned_employee_surname }}
        {% else %} — {% endif %}
      </td>
      <td>
        <a href="{% url 'form_detail_assign' form.form_id %}">Перейти</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<style>
  table {
    border-collapse: collapse;
    width: 100%;
  }
  th,
  td {
    border: 1px solid #ddd;
    padding: 8px;
  }
  th {
    background-color: #f2f2f2;
    text-align: left;
  }
</style>

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Служба технической поддержки</title>
    <link type="image/x-icon" href="favicon.png" rel="shortcut icon">
    <link type="Image/x-icon" href="favicon.png" rel="icon">
    <link rel="stylesheet" href="styles.css">
    <script defer src="script.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>
    <header class="sticky-header">
        <div class="logo">Служба технической поддержки</div>
        <nav>
            <ul class="nav-links">
                <li><a href="http://tech-podderjka64583-site-home.onhh.ru/">Главная</a></li>
                <li><a href="http://tech-podderjka64583-site.onhh.ru/?page_id=137">Текущие заявки</a></li>
                <li><a href="http://tech-podderjka64583-site.onhh.ru/?page_id=98">Сообщения</a></li>
                <li><a href="http://tech-podderjka64583-site.onhh.ru/?page_id=98">Форум</a></li>
                <li><a href="http://tech-podderjka64583-site.onhh.ru/?page_id=26">Отправить заявку</a></li>
                <li><a href="http://tech-podderjka64583-site.onhh.ru/?page_id=137">FAQ</a></li>
            </ul>
        </nav>
    </header>

    <section class="hero">
        <div class="hero-overlay"></div>
        <div class="hero-text">
            <h1>Служба технической поддержки</h1>
            <p>Московский университет имени С.Ю.Витте</p>
            <a href="http://tech-podderjka64583-site.onhh.ru/?page_id=26" class="btn">Оставить запрос</a>
        </div>
    </section>

    <section class="about">
        <p>Слжуба поддержки готова помочь Вам в решении всех вопросов связанных с учебной деятельностью.
             В случае если мы не сможем помочь Вам - мы направим Вас к соответствующему отделу.</p>
    </section>

    <hr>
    <section class="gallery">
        <img src="support-photo.jpg" alt="Техническая поддержка">
        <p>Служба технической поддержки работает на базе Департамента электронного обучения и сопровождения.</p>
    </section>

    <hr>

    <section class="advantages">
        <p>Преимущества нашей системы заключаются в том, что мы готовы помочь Вам по любым вопросам, связанным с учебным процесом в любое время суток!</p>
    </section>

    <div class="btn-block">
        <a href="http://tech-podderjka64583-site.onhh.ru/?page_id=26" class="btn">Оставить запрос</a>
    </div>

    <div class="marquee-container">
        <div class="marquee">Внимание! Все запросы обрабатываются в порядке живой очереди в течении суток!</div>
    </div>

    <footer>
        <p>&copy; 2025 Служба технической поддержки (Студенческая работа)</p>
    </footer>
</body>
</html>

templates/login.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="form-container">
  <h2>Войти</h2>
  <form method="POST">
    {% csrf_token %}
    <label>Имя пользователя:</label>
    <input type="text" name="username" required />
    <label>Пароль:</label>
    <input type="password" name="password" required />
    <button type="submit">Войти</button>
  </form>
  {% for message in messages %}
  <div class="alert error">{{ message }}</div>
  {% endfor %}
</div>
{% endblock %}

templates/my_forms.html
{% extends "base.html" %} {% load static %} {% block title %}Мои
заявки{%endblock%} {% block content %}
<h2>Мои заявки</h2>

{% if assignments %}
<table class="form-table">
  <thead>
    <tr>
      <th>Категория</th>
      <th>Комментарий</th>
      <th>Дата назначения</th>
      <th>Статус</th>
      <th>Действия</th>
    </tr>
  </thead>
  <tbody>
    {% for a in assignments %}
    <tr>
      <td>{{ a.form.category }}</td>
      <td>{{ a.form.comment }}</td>
      <td>{{ a.assigned_at|date:"d.m.Y H:i" }}</td>
      <td>
        <span
          class="status-box {% if a.status == 'обрабатывается' %}yellow{% elif a.status == 'не назначен' %}red{% elif a.status == 'завершен' %}green{% endif %}"
        >
          {{ a.status }}
        </span>
      </td>
      <td>
        <a
          href="{% url 'employee_form_detail' a.form.form_id %}"
          class="btn btn-info"
          >Перейти</a
        >
      </td>
    </tr>

    {% endfor %}
  </tbody>
</table>
{% else %}
<p>У вас нет назначенных заявок.</p>
{% endif %} {% endblock %}

templates/submit_form.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="content">
  <div class="form-container">
    <h2>Оставьте заявку</h2>

    <form method="POST">
      {% csrf_token %}

      <div class="form-group">
        <label for="id_name">Имя</label>
        {{ form.name }}
      </div>

      <div class="form-group">
        <label for="id_email">Электронная почта</label>
        {{ form.email }}
      </div>

      <div class="form-group">
        <label for="id_phone">Номер телефона</label>
        {{ form.phone }}
      </div>

      <div class="form-group">
        <label for="id_category">Категория</label>
        <select name="category" id="id_category">
          <option value="Проблемы с интернетом">Проблемы с интернетом</option>
          <option value="Проблемы с периферийным оборудованием">
            Проблемы с периферийным оборудованием
          </option>
          <option value="Проблемы с электронной почтой">
            Проблемы с электронной почтой
          </option>
          <option value="Другие проблемы">Другие проблемы</option>
        </select>
      </div>

      <div class="form-group">
        <label for="id_comment">Комментарий</label>
        {{ form.comment }}
      </div>

      <button type="submit">Отправить</button>
    </form>

    {% if messages %}
    <div class="messages">
      {% for message in messages %}
      <div class="alert {% if message.tags %}{{ message.tags }}{% endif %}">
        {{ message }}
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}